
# ??????
app.name=server
app.version=1.0
app.main.class=Main

# ?????????? ??????????
src.dir=src/main/java
webapp.dir=src/main/webapp
test.src.dir=src/test/java

# ?????????? ??????
build.dir=build
build.classes.dir= ${build.dir}/classes
build.test.classes.dir=${build.dir}/test-classes
build.jar.dir=${bild.dir}/jar
build.report.dir=${build.dir}/test-reports
build.zip.dir=${build.dir}/team-zip

# --- ????? ????????? ?????????? ---
jar.file=${build.jar.dir}/${app.name}-${app.version}.jar
zip.file=${build.zip.dir}/${app.name}-team-revisions.zip

# ???????????
lib.dir=lib
test.lib.dir=lib/test

# Git
git.revisions.count=4
git.clone.dir=${build.dir}/git-revisions

# Java
javac.source=17
javac.target=17
javac.encoding=UTF-8

# ??????
music.file=resources/build-complete.wav

