
# General
app.name=server
app.version=1.0
app.main.class=Main

# Code sources
src.dir=src/main/java
webapp.dir=src/main/webapp
test.src.dir=src/test/java

# Build
build.dir=build
build.classes.dir=${build.dir}/classes
build.test.classes.dir=${build.dir}/test-classes
build.war.dir=${build.dir}/war
build.report.dir=${build.dir}/test-reports
build.zip.dir=${build.dir}/team-zip

# Build results
war.file=${build.war.dir}/${app.name}-${app.version}.war
zip.file=${build.zip.dir}/${app.name}-team-revisions.zip


# Libraries
lib.dir=lib
test.lib.dir=lib/test

# Git
git.revisions.count=4
git.clone.dir=${build.dir}/git-revisions

# Java
javac.source=17
javac.target=17
javac.encoding=UTF-8

# ??????
music.fail=resources/build-failed.wav
music.success=resources/build-success.wav
